name: build-docker-image

on:
  workflow_call:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ctenex

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
